services:
  postgres:
    image: postgres:15
    container_name: inventory_postgres_test
    restart: always
    environment:
      POSTGRES_DB: inventory_app_test
      POSTGRES_USER: inventory_app_test
      POSTGRES_PASSWORD: inventory_app_test
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inventory_app_test -d inventory_app_test"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: inventory_backend_test
    restart: always
    ports:
      - "5001:5001"
    environment:
      STACK_SECRET_SERVER_KEY: ssk_pszfgybb1nkst3zx1hztj0kmja312ekjnazyt6rkbsgr0

      DB_HOST: postgres
      DB_PORT: 5433
      DB_NAME: inventory_app_test
      DB_USER: inventory_app_test
      DB_PASSWORD: inventory_app_test

      PORT: 5001
      NODE_ENV: development
    volumes:
      - uploads:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./client
    container_name: inventory_frontend_test
    restart: always
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      REACT_APP_API_URL: http://localhost:5001
      REACT_APP_STACK_PROJECT_ID: f07a34bb-9716-428b-93e0-5a58ceeb7cfc
      REACT_APP_STACK_PUBLISHABLE_CLIENT_KEY: pck_6ks2zbrrb38z037m0maqnrt5s1dfnzt2gkpqq369zgyy0
    depends_on:
      - backend

volumes:
  postgres_data:
  uploads:
